#!/bin/bash
source Jimbot/Dependencies/bin/activate
python3 ~/Jimbot/Python/keypressed.py &
python3 ~/Jimbot/Hotword/main.py &
python3 ~/Jimbot/Jimbot.py
deactivate
killall -9 python3 ~/Jimbot/Python/keypressed.py
killall -9 python3 ~/Jimbot/Hotword/main.py
